#ifndef CARD_ID_H
#define CARD_ID_H

#define CARD_TOTAL_COUNT 176

typedef enum {
    // 基本牌
    CARD_BASIC_ATK1 = 1,
    CARD_BASIC_ATK2 = 2,
    CARD_BASIC_ATK3 = 3,
    CARD_BASIC_DEF1 = 4,
    CARD_BASIC_DEF2 = 5,
    CARD_BASIC_DEF3 = 6,
    CARD_BASIC_MOVE1 = 7,
    CARD_BASIC_MOVE2 = 8,
    CARD_BASIC_MOVE3 = 9,
    CARD_BASIC_COMMON = 10,

    // 小紅帽 0
    CARD_REDHOOD_ATK1_QUICK_SHOT = 11,
    CARD_REDHOOD_ATK2_PRECISION_SHOT = 12,
    CARD_REDHOOD_ATK3_FATAL_SHOT = 13,
    CARD_REDHOOD_DEF1_ENERGY_SHIELD = 14,
    CARD_REDHOOD_DEF2_CURRENT_SHIELD = 15,
    CARD_REDHOOD_DEF3_ULTIMATE_SHIELD = 16,
    CARD_REDHOOD_MOVE1_JET = 17,
    CARD_REDHOOD_MOVE2_FIRE_JET = 18,
    CARD_REDHOOD_MOVE3_RAGE_JET = 19,
    CARD_REDHOOD_SPECIAL1_WOLF_HUNGER = 20,
    CARD_REDHOOD_SPECIAL2_SYSTEM_HACK = 21,
    CARD_REDHOOD_SPECIAL3_RAIN_OF_VENGEANCE = 22,

    // 白雪公主 1
    CARD_SNOWWHITE_ATK1_CRYSTAL_SHARD = 23,
    CARD_SNOWWHITE_ATK2_CRYSTAL_VORTEX = 24,
    CARD_SNOWWHITE_ATK3_CRYSTAL_STORM = 25,
    CARD_SNOWWHITE_DEF1_TAINTED_GRACE = 26,
    CARD_SNOWWHITE_DEF2_TAINTED_FEAST = 27,
    CARD_SNOWWHITE_DEF3_TAINTED_CARNIVAL = 28,
    CARD_SNOWWHITE_MOVE1_BROKEN_FANTASY = 29,
    CARD_SNOWWHITE_MOVE2_BROKEN_REALITY = 30,
    CARD_SNOWWHITE_MOVE3_BROKEN_FATE = 31,
    CARD_SNOWWHITE_SPECIAL1_SEVEN_SNAKES_RAGE = 32,
    CARD_SNOWWHITE_SPECIAL2_MAGIC_MIRROR_RAIN = 33,
    CARD_SNOWWHITE_SPECIAL3_BREWED_DISASTER = 34,
    CARD_SNOWWHITE_STATUS_POISON1 = 131,
    CARD_SNOWWHITE_STATUS_POISON2 = 132,
    CARD_SNOWWHITE_STATUS_POISON3 = 133,

    // 睡美人 2
    CARD_SLEEPINGBEAUTY_ATK1_MIND_SHOCK = 35,
    CARD_SLEEPINGBEAUTY_ATK2_MIND_RAGE = 36,
    CARD_SLEEPINGBEAUTY_ATK3_MIND_FURY = 37,
    CARD_SLEEPINGBEAUTY_DEF1_BURST_CHAIN = 38,
    CARD_SLEEPINGBEAUTY_DEF2_BURST_BONE = 39,
    CARD_SLEEPINGBEAUTY_DEF3_BURST_SOUL = 40,
    CARD_SLEEPINGBEAUTY_MOVE1_DARK_TOUCH = 41,
    CARD_SLEEPINGBEAUTY_MOVE2_DARK_ENTANGLE = 42,
    CARD_SLEEPINGBEAUTY_MOVE3_DARK_STRANGLE = 43,
    CARD_SLEEPINGBEAUTY_SPECIAL1_AWAKEN_SLEEP = 44,
    CARD_SLEEPINGBEAUTY_SPECIAL2_DAYMARE = 45,
    CARD_SLEEPINGBEAUTY_SPECIAL3_BLOOD_RECAST = 46,

    // 愛麗絲 3
    CARD_ALICE_ATK1_START_GAME = 47,
    CARD_ALICE_ATK2_REVERSE_GAME = 48,
    CARD_ALICE_ATK3_CONTROL_GAME = 49,
    CARD_ALICE_DEF1_MAGIC_TECHNIQUE = 50,
    CARD_ALICE_DEF2_MENTAL_ILLUSION = 51,
    CARD_ALICE_DEF3_HAT_TRICK = 52,
    CARD_ALICE_MOVE1_WEIRD_AGILITY = 53,
    CARD_ALICE_MOVE2_WEIRD_STEALTH = 54,
    CARD_ALICE_MOVE3_WEIRD_WEIRDNESS = 55,
    CARD_ALICE_SPECIAL1_ENDLESS_PARTY = 56,
    CARD_ALICE_SPECIAL2_WONDERFUL_DAY = 57,
    CARD_ALICE_SPECIAL3_GAME_IN_CONTROL = 58,

    // 花木蘭 4
    CARD_MULAN_ATK1_UNDERESTIMATED = 59,
    CARD_MULAN_ATK2_IRRESISTIBLE = 60,
    CARD_MULAN_ATK3_UNBREAKABLE = 61,
    CARD_MULAN_DEF1_STILLNESS = 62,
    CARD_MULAN_DEF2_SOFTNESS = 63,
    CARD_MULAN_DEF3_WEAK_OVERCOME_STRONG = 64,
    CARD_MULAN_MOVE1_NEVER_RETREAT = 65,
    CARD_MULAN_MOVE2_NO_MERCY = 66,
    CARD_MULAN_MOVE3_NO_FORGIVENESS = 67,
    CARD_MULAN_SPECIAL1_SOARING = 68,
    CARD_MULAN_SPECIAL2_FACE_CHAOS = 69,
    CARD_MULAN_SPECIAL3_THUNDER_STRIKE = 70,

    // 輝夜姬 5
    CARD_KAGUYA_ATK1_ENLIGHTENED_LIGHT = 71,
    CARD_KAGUYA_ATK2_ENLIGHTENED_GLORY = 72,
    CARD_KAGUYA_ATK3_ENLIGHTENED_AVATAR = 73,
    CARD_KAGUYA_DEF1_CONFUSED_ECHO = 74,
    CARD_KAGUYA_DEF2_ANCIENT_ECHO = 75,
    CARD_KAGUYA_DEF3_DIVINE_SUMMON = 76,
    CARD_KAGUYA_MOVE1_FOCUSED_INTROSPECTION = 77,
    CARD_KAGUYA_MOVE2_EPIPHANY = 78,
    CARD_KAGUYA_MOVE3_PAINFUL_PURIFY = 79,
    CARD_KAGUYA_SPECIAL1_BLAZING_BAMBOO = 80,
    CARD_KAGUYA_SPECIAL2_FATED_JUDGEMENT = 81,
    CARD_KAGUYA_SPECIAL3_RESTLESS_BLOOD = 82,

    // 美人魚 6
    CARD_MERMAID_ATK1_SIREN_SUMMON = 83,
    CARD_MERMAID_ATK2_SIREN_SONG = 84,
    CARD_MERMAID_ATK3_SIREN_SCREAM = 85,
    CARD_MERMAID_DEF1_SURGING_RAGE = 86,
    CARD_MERMAID_DEF2_ERUPTING_RAGE = 87,
    CARD_MERMAID_DEF3_REVENGE_RAGE = 88,
    CARD_MERMAID_MOVE1_ABYSS_DEVOUR = 89,
    CARD_MERMAID_MOVE2_ABYSS_INVASION = 90,
    CARD_MERMAID_MOVE3_ABYSS_CONQUEST = 91,
    CARD_MERMAID_SPECIAL1_MERMAID_REVIVAL = 92,
    CARD_MERMAID_SPECIAL2_ANCIENT_AWAKEN = 93,
    CARD_MERMAID_SPECIAL3_PURIFYING_TIDE = 94,

    // 火柴女孩 7
    CARD_MATCHGIRL_ATK1_ILLUSORY_WISH = 95,
    CARD_MATCHGIRL_ATK2_SECRET_HOPE = 96,
    CARD_MATCHGIRL_ATK3_INSATIABLE_DESIRE = 97,
    CARD_MATCHGIRL_DEF1_DEMONIC_SACRIFICE = 98,
    CARD_MATCHGIRL_DEF2_DEMONIC_BET = 99,
    CARD_MATCHGIRL_DEF3_DEMONIC_PACT = 100,
    CARD_MATCHGIRL_MOVE1_WEIGHTLESS_SOUL = 101,
    CARD_MATCHGIRL_MOVE2_INDEBTED_SOUL = 102,
    CARD_MATCHGIRL_MOVE3_BROKEN_SOUL = 103,
    CARD_MATCHGIRL_SPECIAL1_HELLFIRE = 104,
    CARD_MATCHGIRL_SPECIAL2_DOOM = 105,
    CARD_MATCHGIRL_SPECIAL3_GREED_CURSE = 106,
    CARD_MATCHGIRL_ITEM_MATCH = 134,

    // 桃樂絲 8
    CARD_DOROTHY_ATK1_TARGET_CONFIRM = 107,
    CARD_DOROTHY_ATK2_TARGET_LOCK = 108,
    CARD_DOROTHY_ATK3_TARGET_CLEAR = 109,
    CARD_DOROTHY_DEF1_MIND_PROBE = 110,
    CARD_DOROTHY_DEF2_DEEP_SEARCH = 111,
    CARD_DOROTHY_DEF3_READ_COMPLETE = 112,
    CARD_DOROTHY_MOVE1_FIND_ENEMY = 113,
    CARD_DOROTHY_MOVE2_ENTER_SIGHT = 114,
    CARD_DOROTHY_MOVE3_MISSION_END = 115,
    CARD_DOROTHY_SPECIAL1_LION = 116,
    CARD_DOROTHY_SPECIAL2_TINMAN = 117,
    CARD_DOROTHY_SPECIAL3_SCARECROW = 118,

    // 山魯佐德 9
    CARD_SCHEHERAZADE_ATK1_ERASE_DREAM = 119,
    CARD_SCHEHERAZADE_ATK2_DESTROY_MEMORY = 120,
    CARD_SCHEHERAZADE_ATK3_STRANGLE_EXISTENCE = 121,
    CARD_SCHEHERAZADE_DEF1_IMMERSE_NET = 122,
    CARD_SCHEHERAZADE_DEF2_INDULGE_NET = 123,
    CARD_SCHEHERAZADE_DEF3_DISSOLVE_NET = 124,
    CARD_SCHEHERAZADE_MOVE1_WATCHFUL_EYE = 125,
    CARD_SCHEHERAZADE_MOVE2_MANIPULATE_HAND = 126,
    CARD_SCHEHERAZADE_MOVE3_DOMINATE_BRAIN = 127,
    CARD_SCHEHERAZADE_SPECIAL1_SYSTEM_DELETE = 128,
    CARD_SCHEHERAZADE_SPECIAL2_UNABLE_TO_EXTRICATE = 129,
    CARD_SCHEHERAZADE_SPECIAL3_CUT_OFF_PATH = 130,

    // 蛻變牌
    // 小紅帽
    CARD_REDHOOD_METAMORPH1_OVERLOAD_BURN = 135,
    CARD_REDHOOD_METAMORPH2_HOOD_SYSTEM = 136,
    CARD_REDHOOD_METAMORPH3_MUTATION_SENSE = 137,
    CARD_REDHOOD_METAMORPH4_ONBOARD_CACHE = 138,
    // 白雪公主
    CARD_SNOWWHITE_METAMORPH1_CRYSTAL_COFFIN = 139,
    CARD_SNOWWHITE_METAMORPH2_FALLEN_CALAMITY = 140,
    CARD_SNOWWHITE_METAMORPH3_TOXIC_EROSION = 141,
    CARD_SNOWWHITE_METAMORPH4_PURIST_POISON = 142,
    // 睡美人
    CARD_SLEEPINGBEAUTY_METAMORPH1_BLOODLETTING = 143,
    CARD_SLEEPINGBEAUTY_METAMORPH2_BLOOD_RITUAL = 144,
    CARD_SLEEPINGBEAUTY_METAMORPH3_MENTAL_BARRIER = 145,
    CARD_SLEEPINGBEAUTY_METAMORPH4_FORCED_TREATMENT = 146,
    // 愛麗絲
    CARD_ALICE_METAMORPH1_OFF_WITH_HER_HEAD = 147,
    CARD_ALICE_METAMORPH2_WONDERLAND_DESCENT = 148,
    CARD_ALICE_METAMORPH3_ALL_MAD = 149,
    CARD_ALICE_METAMORPH4_SHOWTIME = 150,
    // 花木蘭
    CARD_MULAN_METAMORPH1_QI_FLOW = 151,
    CARD_MULAN_METAMORPH2_DOMINATE_FATE = 152,
    CARD_MULAN_METAMORPH3_CHARGE = 153,
    CARD_MULAN_METAMORPH4_BEFORE_STORM = 154,
    // 輝夜姬
    CARD_KAGUYA_METAMORPH1_PENALTY_TIME = 155,
    CARD_KAGUYA_METAMORPH2_BLOOD_MOON = 156,
    CARD_KAGUYA_METAMORPH3_SPIRIT_INSTINCT = 157,
    CARD_KAGUYA_METAMORPH4_MOONLIT_MEDITATION = 158,
    // 美人魚
    CARD_MERMAID_METAMORPH1_STORM_EROSION = 159,
    CARD_MERMAID_METAMORPH2_MYSTIC_RESONANCE = 160,
    CARD_MERMAID_METAMORPH3_DAUGHTER_OF_SEA = 161,
    CARD_MERMAID_METAMORPH4_UNDERCURRENT = 162,
    // 火柴女孩
    CARD_MATCHGIRL_METAMORPH1_PAINFUL_RITUAL = 163,
    CARD_MATCHGIRL_METAMORPH2_INDULGENT_DESIRE = 164,
    CARD_MATCHGIRL_METAMORPH3_DEMONIC_GAZE = 165,
    CARD_MATCHGIRL_METAMORPH4_FLAME_TEASE = 166,
    CARD_MATCHGIRL_METAMORPH5_DESIRE_TEASE = 167,
    CARD_MATCHGIRL_METAMORPH6_FATE_TEASE = 168,
    // 桃樂絲
    CARD_DOROTHY_METAMORPH1_KILL_COMMAND = 169,
    CARD_DOROTHY_METAMORPH2_BEYOND_MACHINE = 170,
    CARD_DOROTHY_METAMORPH3_EXECUTION_GRANTED = 171,
    CARD_DOROTHY_METAMORPH4_NOWHERE_TO_HIDE = 172,
    // 山魯佐德
    CARD_SCHEHERAZADE_METAMORPH1_FATE_HAND = 173,
    CARD_SCHEHERAZADE_METAMORPH2_REWRITE_DESIRE = 174,
    CARD_SCHEHERAZADE_METAMORPH3_REORGANIZE_THOUGHT = 175,
    CARD_SCHEHERAZADE_METAMORPH4_FAIRYTALE_WEAVER = 176
} CardID;

#endif

