#ifndef CARD_ID_H
#define CARD_ID_H

#define CARD_TOTAL_COUNT 176

typedef enum {
	// 基本牌
	CARD_LV1_ATTACK       = 1,   // LV1攻擊牌
	CARD_LV2_ATTACK       = 2,   // LV2攻擊牌
	CARD_LV3_ATTACK       = 3,   // LV3攻擊牌
	CARD_LV1_DEFENSE      = 4,   // LV1防禦牌
	CARD_LV2_DEFENSE      = 5,   // LV2防禦牌
	CARD_LV3_DEFENSE      = 6,   // LV3防禦牌
	CARD_LV1_MOVE         = 7,   // LV1移動牌
	CARD_LV2_MOVE         = 8,   // LV2移動牌
	CARD_LV3_MOVE         = 9,   // LV3移動牌
	CARD_UNIVERSAL        = 10,  // 通用牌

	// 小紅帽 (Group 0)
	CARD_REDHOOD_QUICK_SHOT      = 11, // 快速射擊
	CARD_REDHOOD_PRECISION_SHOT  = 12, // 精準射擊
	CARD_REDHOOD_DEADLY_SNIPER   = 13, // 致命狙擊
	CARD_REDHOOD_ENERGY_SHIELD   = 14, // 能量護盾
	CARD_REDHOOD_ELECTRIC_SHIELD = 15, // 電流護盾
	CARD_REDHOOD_ULTIMATE_SHIELD  = 16, // 終極護盾
	CARD_REDHOOD_BALLISTIC_JET    = 17, // 彈道噴射
	CARD_REDHOOD_FIRE_JET         = 18, // 火力噴射
	CARD_REDHOOD_RAGE_JET         = 19, // 暴怒噴射
	CARD_REDHOOD_WOLF_DEVOUR      = 20, // 餓狼吞噬
	CARD_REDHOOD_SYSTEM_HACK      = 21, // 系統入侵
	CARD_REDHOOD_REINFORCE_RAIN   = 22, // 復仇之雨

	// 白雪公主 (Group 1)
	CARD_WHITESNOW_CRYSTAL_SHARD     = 23, // 水晶碎片
	CARD_WHITESNOW_CRYSTAL_VORTEX    = 24, // 水晶漩渦
	CARD_WHITESNOW_CRYSTAL_STORM     = 25, // 水晶風暴
	CARD_WHITESNOW_TAINTED_GRACE     = 26, // 玷污的恩惠
	CARD_WHITESNOW_TAINTED_FEAST     = 27, // 玷污的盛筵
	CARD_WHITESNOW_TAINTED_CARNIVAL  = 28, // 玷污的狂歡
	CARD_WHITESNOW_SHATTERED_ILLUSION= 29, // 破碎的幻想
	CARD_WHITESNOW_SHATTERED_REALITY = 30, // 破碎的現實
	CARD_WHITESNOW_SHATTERED_DESTINY = 31, // 破碎的命運
	CARD_WHITESNOW_SEVEN_SNAKES_WRATH= 32, // 七蛇之怒
	CARD_WHITESNOW_MAGIC_MIRROR_RAIN = 33, // 魔鏡之雨
	CARD_WHITESNOW_BREWED_CALAMITY    = 34, // 醞釀之災
	CARD_WHITESNOW_POISON1           = 131, // 中毒1
	CARD_WHITESNOW_POISON2           = 132, // 中毒2
	CARD_WHITESNOW_POISON3           = 133, // 中毒3

	// 睡美人 (Group 2)
	CARD_SLEEPINGBEAUTY_MIND_TREMOR   = 35, // 心靈震顫
	CARD_SLEEPINGBEAUTY_MIND_RAGE     = 36, // 心靈之怒
	CARD_SLEEPINGBEAUTY_MIND_FURY     = 37, // 心靈狂怒
	CARD_SLEEPINGBEAUTY_EXPLOSIVE_CHAIN= 38, // 爆裂之鎖
	CARD_SLEEPINGBEAUTY_EXPLOSIVE_BONE= 39, // 爆裂之骨
	CARD_SLEEPINGBEAUTY_EXPLOSIVE_SOUL = 40, // 爆裂之魂
	CARD_SLEEPINGBEAUTY_DARK_TOUCH     = 41, // 黑暗碰觸
	CARD_SLEEPINGBEAUTY_DARK_ENTANGLE  = 42, // 黑暗糾纏
	CARD_SLEEPINGBEAUTY_DARK_STRANGLE  = 43, // 黑暗絞殺
	CARD_SLEEPINGBEAUTY_AWAKEN_SLEEP   = 44, // 喚醒沉睡
	CARD_SLEEPINGBEAUTY_DAYMARE        = 45, // 白日夢魘
	CARD_SLEEPINGBEAUTY_BLOOD_REFORGE  = 46, // 血脈重鑄

	// 愛麗絲 (Group 3)
	CARD_ALICE_OPENING_GAME     = 47, // 開啟牌局
	CARD_ALICE_TURNING_GAME     = 48, // 扭轉牌局
	CARD_ALICE_CONTROL_GAME     = 49, // 操控牌局
	CARD_ALICE_MAGIC_SKILL      = 50, // 魔力技巧
	CARD_ALICE_MENTAL_ILLUSION  = 51, // 精神幻術
	CARD_ALICE_HAT_TRICK        = 52, // 帽子戲法
	CARD_ALICE_EERIE_AGILITY    = 53, // 詭異的敏捷
	CARD_ALICE_EERIE_STEALTH    = 54, // 詭異的隱蔽
	CARD_ALICE_EERIE_EERINESS   = 55, // 詭異的詭異
	CARD_ALICE_ENDLESS_PARTY    = 56, // 無休止的派對
	CARD_ALICE_WONDERFUL_DAY    = 57, // 精彩的奇妙日
	CARD_ALICE_GAME_CONTROL     = 58, // 遊戲盡在掌控

	// 花木蘭 (Group 4)
	CARD_MULAN_NOT_TO_BE_UNDERES = 59, // 不容小覷
	CARD_MULAN_UNSTOPPABLE       = 60, // 勢不可擋
	CARD_MULAN_UNBREAKABLE       = 61, // 堅不可摧
	CARD_MULAN_QUIET_CONTROL     = 62, // 以靜制動
	CARD_MULAN_SOFT_OVER_POWER    = 63, // 以柔克剛
	CARD_MULAN_WEAK_WIN_STRONG   = 64, // 以弱勝強
	CARD_MULAN_NEVER_RETREAT     = 65, // 永不退縮
	CARD_MULAN_RUTHLESS          = 66, // 毫不留情
	CARD_MULAN_NO_FORGIVENESS     = 67, // 絕不饒恕
	CARD_MULAN_SOAR              = 68, // 氣沖雲霄
	CARD_MULAN_CONFRONT_CHAOS    = 69, // 直面混沌
	CARD_MULAN_THUNDER_STRIKE    = 70, // 雷霆一擊

	// 輝夜姬 (Group 5)
	CARD_KAGUYA_ENLIGHTENMENT         = 71, // 領悟的光芒
	CARD_KAGUYA_ENLIGHTENED_GLORY      = 72, // 領悟的榮耀
	CARD_KAGUYA_ENLIGHTENED_AVATAR     = 73, // 領悟的化身
	CARD_KAGUYA_CONFUSED_ECHO          = 74, // 困惑的回聲
	CARD_KAGUYA_ANCIENT_ECHO           = 75, // 久遠的回響
	CARD_KAGUYA_DIVINE_SUMMON          = 76, // 神性的召換
	CARD_KAGUYA_CONCENTRATED_INTROSPECTION = 77, // 專注的自省
	CARD_KAGUYA_ENLIGHTENED_DECISION   = 78, // 頓悟的決心
	CARD_KAGUYA_PAIN_PURGE             = 79, // 痛徹的淨化
	CARD_KAGUYA_SCORCHING_BAMBOO_SWORD  = 80, // 炙熱的竹刀
	CARD_KAGUYA_FATED_JUDGMENT         = 81, // 注定的審判
	CARD_KAGUYA_FEROCIOUS_BLOOD        = 82, // 躁動的血性

	// 美人魚 (Group 6)
	CARD_MERMAID_SEA_SIREN_SUMMON = 83, // 海妖的召喚
	CARD_MERMAID_SEA_SIREN_SONG    = 84, // 海妖的歌聲
	CARD_MERMAID_SEA_SIREN_SHRIEK   = 85, // 海妖的尖嘯
	CARD_MERMAID_RAGING_WAVE       = 86, // 洶湧之怒
	CARD_MERMAID_ERUPTIVE_FURY      = 87, // 噴薄之怒
	CARD_MERMAID_REVENGE_FURY       = 88, // 復仇之怒
	CARD_MERMAID_ABYSS_DEVOUR       = 89, // 深淵的蠶食
	CARD_MERMAID_ABYSS_INVASION     = 90, // 深淵的入侵
	CARD_MERMAID_ABYSS_CONQUEST     = 91, // 深淵的征服

	// 火柴女孩 (Group 7)
	CARD_MATCHGIRL_ILLUSORY_WISH    = 95,  // 虛幻的願望
	CARD_MATCHGIRL_CLOAKED_DESIRE   = 96,  // 隱密的期望
	CARD_MATCHGIRL_INSATIABLE_LUXURY= 97,  // 無厭的奢望
	CARD_MATCHGIRL_DEMONIC_SACRIFICE = 98,  // 惡魔的祭品
	CARD_MATCHGIRL_DEMONIC_BET      = 99,  // 惡魔的賭注
	CARD_MATCHGIRL_DEMONIC_CONTRACT = 100, // 惡魔的契約
	CARD_MATCHGIRL_WEIGHTLESS_SOUL  = 101, // 失重的靈魂
	CARD_MATCHGIRL_INDICTED_SOUL    = 102, // 虧欠的靈魂
	CARD_MATCHGIRL_SHATTERED_SOUL   = 103, // 殘破的靈魂
	CARD_MATCHGIRL_HELLFIRE         = 104, // 地獄烈焰
	CARD_MATCHGIRL_DOOM_DESCENT      = 105, // 厄運降臨
	CARD_MATCHGIRL_GREED_CURSE       = 106, // 貪婪詛咒
	CARD_MATCHGIRL_FIREMATCH         = 134, // 火柴

	// 桃樂絲 (Group 8)
	CARD_DOROTHY_TARGET_CONFIRM = 107, // 目標確認
	CARD_DOROTHY_TARGET_LOCK    = 108, // 目標鎖定
	CARD_DOROTHY_TARGET_CLEAR   = 109, // 目標清除
	CARD_DOROTHY_MIND_PROBE     = 110, // 思想刺探
	CARD_DOROTHY_DEEP_SEARCH    = 111, // 深度搜索
	CARD_DOROTHY_READ_COMPLETE  = 112, // 讀取完畢
	CARD_DOROTHY_ENEMY_TRACE    = 113, // 發現敵蹤
	CARD_DOROTHY_ENTER_VISION   = 114, // 進入視野
	CARD_DOROTHY_MISSION_END    = 115, // 使命終結
	CARD_DOROTHY_LION           = 116, // 獅子
	CARD_DOROTHY_TIN_MAN        = 117, // 鐵皮人
	CARD_DOROTHY_SCARECROW      = 118, // 稻草人

	// 山魯佐德 (Group 9)
	CARD_SCHEHERAZADE_ERADICATE_DREAM  = 119, // 消除夢境
	CARD_SCHEHERAZADE_DESTROY_MEMORY     = 120, // 銷毀記憶
	CARD_SCHEHERAZADE_STRANGLE_EXISTENCE = 121, // 扼殺存在
	CARD_SCHEHERAZADE_IMMERSED_NET        = 122, // 浸沒之網
	CARD_SCHEHERAZADE_OBSESSED_NET       = 123, // 沈迷之網
	CARD_SCHEHERAZADE_DISSOLVE_NET       = 124, // 消融之網
	CARD_SCHEHERAZADE_EYE_OF_SURVEILLANCE = 125, // 監視之眼
	CARD_SCHEHERAZADE_HAND_OF_CONTROL     = 126, // 操縱之手
	CARD_SCHEHERAZADE_DOMINATE_BRAIN     = 127, // 支配之腦
	CARD_SCHEHERAZADE_SYSTEM_DELETE      = 128, // 系統刪除
	CARD_SCHEHERAZADE_CANNOT_BREAK       = 129, // 無法自拔
	CARD_SCHEHERAZADE_CUT_OFF_PATH       = 130, // 切斷通路

	// 蛻變牌 – 小紅帽
	CARD_REDHOOD_OVERCLOCK_BURN = 135, // 過載燃燒
	CARD_REDHOOD_HOOD_SYSTEM    = 136, // 兜帽系統
	CARD_REDHOOD_MUTATION_SENSOR = 137, // 變異感應
	CARD_REDHOOD_ONBOARD_CACHE   = 138, // 板載緩存

	// 蛻變牌 – 白雪公主
	CARD_WHITESNOW_CRYSTAL_COFFIN   = 139, // 水晶之棺
	CARD_WHITESNOW_FALLEN_CALAMITY   = 140, // 墮落之劫
	CARD_WHITESNOW_CARNIVAL_OF_TERROR= 141, // 劇毒之蝕
	CARD_WHITESNOW_PURE_POISON       = 142, // 至純之毒

	// 蛻變牌 – 睡美人
	CARD_SLEEPINGBEAUTY_BLOOD_LET   = 143, // 放血療法
	CARD_SLEEPINGBEAUTY_BLOOD_RITUAL = 144, // 血祭之禮
	CARD_SLEEPINGBEAUTY_MENTAL_BARRIER= 145, // 精神屏障
	CARD_SLEEPINGBEAUTY_FORCE_HEAL   = 146, // 強制治療

	// 蛻變牌 – 愛麗絲
	CARD_ALICE_CHOP_HEAD         = 147, // 砍掉她的頭
	CARD_ALICE_WONDERLAND        = 148, // 仙境降臨
	CARD_ALICE_WE_ARE_ALL_INSANE = 149, // 我們全是瘋子
	CARD_ALICE_START_MY_SHOW     = 150, // 開始我的表演

	// 蛻變牌 – 花木蘭
	CARD_MULAN_FULL_OF_QI    = 151, // 氣慣全身
	CARD_MULAN_CONTROL_FATE  = 152, // 主宰命運
	CARD_MULAN_CHARGE        = 153, // 長驅直入
	CARD_MULAN_STORM_BEFORE  = 154, // 暴風前夕

	// 蛻變牌 – 輝夜姬
	CARD_KAGUYA_PUNISHMENT_MOMENT = 155, // 懲戒時刻
	CARD_KAGUYA_BLOODY_MOONLIGHT  = 156, // 血色月光
	CARD_KAGUYA_SPIRIT_INSTINCT   = 157, // 靈性本能
	CARD_KAGUYA_MOON_REFLECTION   = 158, // 月下沉思

	// 蛻變牌 – 美人魚
	CARD_MERMAID_STORM_EROSION    = 159, // 暴風之蝕
	CARD_MERMAID_MYSTIC_RESONANCE = 160, // 神秘共鳴
	CARD_MERMAID_DAUGHTER_OF_THE_SEA = 161, // 海的女兒
	CARD_MERMAID_DARK_TIDE        = 162, // 暗潮湧動
	// 美人魚必殺牌 (依照編號)
	CARD_MERMAID_REVIVAL          = 92,  // 人魚復興
	CARD_MERMAID_ANCIENT_AWAKENING= 93,  // 遠古甦醒
	CARD_MERMAID_PURIFYING_TIDE   = 94,  // 淨化之潮

	// 蛻變牌 – 火柴女孩
	CARD_MATCHGIRL_PAINFUL_RITUAL = 163, // 痛苦的儀式
	CARD_MATCHGIRL_INDULGENT_DESIRE = 164, // 放縱的渴望
	CARD_MATCHGIRL_DEMONIC_GAZE    = 165, // 魔鬼的凝視
	CARD_MATCHGIRL_FIRE_MOCKERY    = 166, // 火焰的捉弄
	CARD_MATCHGIRL_DEMANDED_DESIRE = 167, // 欲望的捉弄
	CARD_MATCHGIRL_FATE_MOCKERY    = 168, // 命運的捉弄

	// 蛻變牌 – 桃樂絲
	CARD_DOROTHY_KILL_COMMAND     = 169, // 殺戮指令
	CARD_DOROTHY_BEYOND_MACHINE   = 170, // 超越機器
	CARD_DOROTHY_APPROVED_EXECUTION = 171, // 獲准極刑
	CARD_DOROTHY_INVISIBLE         = 172, // 無所遁形

	// 蛻變牌 – 山魯佐德
	CARD_SCHEHERAZADE_HAND_OF_FATE    = 173, // 命運之手
	CARD_SCHEHERAZADE_REWRITE_DESIRE  = 174, // 改寫欲望
	CARD_SCHEHERAZADE_REASSEMBLE_MIND = 175, // 重組思想
	CARD_SCHEHERAZADE_FABLE_WEAVER    = 176  // 童話編織者
} CardID;

#endif

