#ifndef CARD_ID_H
#define CARD_ID_H

typedef enum {
    CARD_REDHOOD_ATK1_QUICK_SHOT = 11,
    CARD_REDHOOD_ATK2_PRECISION_SHOT,
    CARD_REDHOOD_ATK3_FATAL_SHOT,
    CARD_REDHOOD_ATK_METAMORPH1_OVERLOAD,
    CARD_REDHOOD_ATK_METAMORPH2_CACHE,

    CARD_REDHOOD_DEF1_ENERGY_SHIELD,
    CARD_REDHOOD_DEF2_CURRENT_SHIELD,
    CARD_REDHOOD_DEF3_ULTIMATE_SHIELD,
    CARD_REDHOOD_DEF_METAMORPH1_HOOD_SYSTEM,
    CARD_REDHOOD_DEF_METAMORPH2_CACHE,

    CARD_REDHOOD_MOVE1_JET,
    CARD_REDHOOD_MOVE2_FIRE_JET,
    CARD_REDHOOD_MOVE3_RAGE_JET,
    CARD_REDHOOD_MOVE_METAMORPH1_RANGE_BOOST,
    CARD_REDHOOD_MOVE_METAMORPH2_CACHE,

    CARD_REDHOOD_SPECIAL1_WOLF_HUNGER,
    CARD_REDHOOD_SPECIAL2_SYSTEM_HACK,
    CARD_REDHOOD_SPECIAL3_RAIN_OF_VENGEANCE,

    CARD_TOTAL_COUNT = 176
} CardID;

#endif

